entries/forms.py
import wtforms 
from wtforms.validators import DataRequired

from models import Entry, Tag


class TagField(wtforms.StringField):
    def _value(self):
        if self.data:
            # Display tags as a comma-separated list.
            return ', '.join([tag.name for tag in self.data])
        return ''
        
    def get_tags_from_string(self, tag_string):
        raw_tags = tag_string.split(',')
        # Filter out any empty tag names.
        tag_names = [name.strip() for name in raw_tags if name.strip()]
        # Query the database and retrieve any tags we have already saved.
        existing_tags = Tag.query.filter(Tag.name.in_(tag_names))
        # Determine which tag names are new.
        new_names = set(tag_names) - set([tag.name for tag in existing_tags])
        # Create a list of unsaved Tag instances for the new tags.
        new_tags = [Tag(name=name) for name in new_names]
        # Return all the existing tags + all the new, unsaved tags.
        return list(existing_tags) + new_tags
        
    def process_formdata(self, valuelist):
        if valuelist:
            self.data = self.get_tags_from_string(valuelist[0])
        else:
            self.data = []


class EntryForm(wtforms.Form):
    title = wtforms.StringField('Title', validators=[DataRequired()])
    body = wtforms.TextAreaField('Body', validators=[DataRequired()])
    status = wtforms.SelectField('Entry status',
        choices=(
            (Entry.STATUS_PUBLIC, 'Public'),
            (Entry.STATUS_DRAFT, 'Draft')),
        coerce=int)
    post_image = wtforms.FileField('Post Image', description="Only 'png', 'jpg', 'jpeg', 'gif' formats.")

    tags = TagField('Tags', description='Seperate multiple tags with commas')

    def save_entry(self, entry):
        self.populate_obj(entry)
        entry.generate_slug()
        return entry

entries/blueprint.py
import os
from flask import Blueprint, render_template, request, flash, redirect, url_for
from werkzeug.utils import secure_filename
from helpers import object_list
from models import Entry, Tag
from app import app, db
from entries.forms import EntryForm

# INIT BLUEPRINTS
entries = Blueprint('entries', __name__, template_folder='templates')


# HELPER FUNCTIONS
# Helper function for additionaly filter results based on search query - 'q'
def entry_list(template, query, **context):
    valid_statuses = (Entry.STATUS_PUBLIC, Entry.STATUS_DRAFT)
    query = query.filter(Entry.status.in_(valid_statuses))
    results = []
    search = request.args.get('q')
    if search:
        query = query.filter(
            (Entry.body.contains(search)) |
            (Entry.title.contains(search)))
        results = query.all()
        if not results:
            flash(f'There were no matches for your search "{search}".', 'danger')
    return object_list(template, query, **context)

# Recheck database for specific entry slug with valid status
def get_entry_or_404(slug):
    valid_statuses = (Entry.STATUS_PUBLIC, Entry.STATUS_DRAFT) 
    return (Entry.query.filter((Entry.slug == slug) & (Entry.status.in_(valid_statuses))).first_or_404())

# Checks if images has right format
def allowed_image(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in app.config['ALLOWED_EXTENSIONS']

# Entries count of particular tag
def tag_indexing(tags):
    tags_index = []
    for tag in tags:
        # If entries of tag == 0 then delete this tag
        if tag.entries.count() == 0:
            db.session.delete(tag)
        tags_index.append(tag.entries.count())
    db.session.commit()
    while 0 in tags_index:
        tags_index.remove(0)
    return tags_index


# URL ROUTES
@entries.route('/')
def index():
    entries = Entry.query.order_by(Entry.created_timestamp.desc())
    tags = Tag.query.order_by(Tag.name.asc()).all()
    tags_index = tag_indexing(tags)
    return entry_list('entries/index.html', entries,
        title='Jonas Laurinaitis - Blog Posts', tags=zip(tags, tags_index))

@entries.route('/categories/')
def tag_index():
    tags = Tag.query.order_by(Tag.name.asc())
    tags_index = [len(tag.entries.all()) for tag in tags]
    return object_list('entries/tag_index.html', tags, title= "Blog Categories", tags_index=tags_index )

@entries.route('/category/<slug>/')
def tag_detail(slug):
    tag = Tag.query.filter(Tag.slug == slug).first_or_404()
    entries = tag.entries.order_by(Entry.created_timestamp.desc())
    return entry_list('entries/tag_detail.html', entries, tag=tag, title="Blog Category - " + tag.name)

# Create
@entries.route('/create/', methods=['GET', 'POST'])
def create():
    if request.method == 'POST':
        form = EntryForm(request.form)
        if form.validate():
            image_file = request.files['post_image']
            if image_file.filename == '':
                flash('No selected file!', 'danger')
                return redirect(request.url)
            if not allowed_image(image_file.filename):
                flash("Wrong image format! Only 'png', 'jpg', 'jpeg', 'gif' formats.", "danger")
                return redirect(request.url)
            filename_path = os.path.join(app.config['IMAGES_DIR'], secure_filename(image_file.filename))
            image_file.save(filename_path)
            img_url = image_file.filename
            entry = Entry(
                title=form.title.data,
                body=form.body.data,
                image_url=img_url,
                status=form.status.data,
                tags=form.tags.data
                )
            db.session.add(entry)
            db.session.commit()
            flash('Entry "%s" created successfully.' % entry.title, 'success')
            return redirect(url_for('entries.detail', slug=entry.slug))

    else:
        form = EntryForm()
    
    return render_template('entries/create.html', form=form, title="Create New Post")

# POST- detail view   
@entries.route('/<slug>/')
def detail(slug):
    entry = get_entry_or_404(slug)
    return render_template('entries/detail.html', entry=entry, title="Blog Post - " + entry.title)

# Edit
@entries.route('/<slug>/edit/', methods=['GET', 'POST'])
def edit(slug):
    entry = get_entry_or_404(slug)
    if request.method == 'POST':
        form = EntryForm(request.form, obj=entry)
        if form.validate():
            entry.title = form.title.data
            entry.body = form.body.data
            entry.status = form.status.data
            entry.tags = form.tags.data 
            db.session.add(entry)
            db.session.commit()
            flash(f'Entry "{entry.title}" has been saved.', 'success')
            return redirect(url_for('entries.detail',
            slug=entry.slug))
    else:
        form = EntryForm(obj=entry)

    return render_template('entries/edit.html', entry=entry, form=form)

# Delete
@entries.route('/<slug>/delete/', methods=['GET', 'POST'])
def delete(slug):
    entry = get_entry_or_404(slug)
    if request.method == 'POST':
        filename_path = os.path.join(app.config['IMAGES_DIR'], entry.image_url)
        os.remove(filename_path)
        db.session.delete(entry)
        db.session.commit()
        flash('Entry "%s" has been deleted.' % entry.title, 'success')
        return redirect(url_for('entries.index'))
    
    return render_template('entries/delete.html', entry=entry)
 

entries/templates/entries/create.html
{% extends "layoutfooteroff.html" %}
{% from "macros/form_field.html" import form_field %}

{% block main %}
<!-- Entries Create Form Page -->
<section class="register-form">
  <div class="container">

    <form action="{{ url_for('entries.create') }}" enctype="multipart/form-data" method="POST" novalidate>
      <div class="form-group">
        <legend class="border-bottom my-4 pb-2">Create New Post Entry</legend>
        {% for field in form %}
          {{ form_field(field) }}
        {% endfor %}
      </div>
      <div class="form-group">
        <div class="col-sm-3 col-sm-9 p-0">
          <button type="submit" class="btn btn-success">Create</button>
          <a class="btn btn-outline-success" href="{{ url_for('entries.index')}}">Cancel</a>
        </div>
      </div>
    </form>
  
  <!-- End Container -->
  </div>
</section>
{% endblock %}

entries/templates/entries/delete.html
{% extends "layoutfooteroff.html" %}

{% block main %}
<!-- Edit Form Page -->
<section class="delele-form">
  <div class="container">
    <h1 class="mt-4">{{ entry.title }}</h1>

    <form action="{{ url_for('entries.delete', slug=entry.slug) }}" method="POST" novalidate>
      <fieldset>
        <legend>Delete this entry?</legend>
        <button class="btn btn-danger" type="submit">Delete</button>
        <a class="btn" href="{{ url_for('entries.detail', slug=entry.
           slug) }}">Cancel</a>
      </fieldset>
    </form>

    <!-- End Container -->
  </div>
</section>
{% endblock %}

entries/templates/entries/detail.html
{% extends "layout.html" %}


{% block main %}
<!-- Post Detail Page -->
<div class="container">
  <div class="row">

    <!-- Content Column -->
    <div class="col-md-8">
      <!-- Title -->
      <h1 class="mt-4">{{ entry.title }}</h1>
      <!-- Author -->
      <div class="ro">

      </div>
      <p class="lead"> by <a href="{{ url_for('about')}}">Jonas</a></p>
      <hr>
      <!-- Date/Time -->
      <p>Posted on 
        {{ entry.created_timestamp.strftime('%B %d, %Y') }} at
        {{ entry.created_timestamp.strftime('%H:%M') }}</p>
      <hr>
      <!-- Preview Image -->
      <img class="img-fluid rounded" src="{{ url_for('static', filename='/img/' + entry.image_url )}}" alt="{{ entry.title }}">
      <hr>
      <p class=>{{ entry.body }}</p>
      <hr>
    </div>

    <!-- Sidebar Column -->
    <div class="col-md-4">
      <!-- Edit/Delete -->
      <div class="card my-4">
        <div class="h5 card-header">Post options</div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item"><a href="{{ url_for('entries.edit', slug=entry.slug) }}">Edit</a></li>
          <li class="list-group-item"><a href="{{ url_for('entries.delete', slug=entry.slug) }}">Delete</a></li>
        </ul>
      </div>
      <!-- Post Tags -->
      <div class="card my-4">
        <h5 class="card-header"><a href="{{ url_for('entries.tag_index') }}">Categories</a></h5>
        <div class="card-body">
          <ul class="list-unstyled mb-0">
            {% for tag in entry.tags %}
            <li><a href="{{ url_for('entries.tag_detail', slug=tag.slug)
                            }}">{{ tag.name }}</a></li>
            {% endfor %}
          </ul>
        </div>
      </div>
    </div>

    <!-- End Row -->
  </div>
  <!-- End Container -->
</div>
{% endblock %}

entries/templates/entries/edit.html
{% extends "layoutfooteroff.html" %}

{% block main %}
<!-- Edit Form Page -->
<section class="edit-form">
  <div class="container">

    <form action="{{ url_for('entries.edit', slug=entry.slug) }}" method="POST" novalidate>
      <div class="form-group">
        <legend class="border-bottom my-4"><span class="h3">Edit:</span> <small class="text-muted">{{ entry.title }}</small></legend>
        <div class="form-group">
          {{ form.title.label(class="form-control-label") }}

          {% if form.title.errors %}
          {{ form.title(class="form-control is-invalid") }}
          <div class="invalid-feedback">
              {% for error in form.title.errors %}
              <span>{{ error }}</span>
              {% endfor %}
          </div>
          {% else %}
          {{ form.title(class="form-control") }}
          {% endif %}
        </div>
        <div class="form-group">
          {{ form.body.label(class="form-control-label") }}

          {% if form.body.errors %}
          {{ form.body(class="form-control is-invalid") }}
          <div class="invalid-feedback">
              {% for error in form.body.errors %}
              <span>{{ error }}</span>
              {% endfor %}
          </div>
          {% else %}
          {{ form.body(class="form-control") }}
          {% endif %}
        </div>
        <div class="form-group">
          {{ form.status.label(class="form-control-label") }}
          {{ form.status(class="form-control") }}
        </div>
        <div class="form-group">
          <label>Post Image</label>
          <select multiple class="form-control">
              <option>{{ entry.image_url }}</option>
          </select>
          <small class="form-text text-muted">Post picture not editable</small>
        </div>
        <div class="form-group">
          {{ form.tags.label(class="form-control-label") }}
          {{ form.tags(class="form-control") }}
          <small class="form-text text-muted">{{ form.tags.description|safe }}</small>
        </div>
        
      </div>
      <div class="form-group">
        <div class="col-sm-3 col-sm-9 p-0">
          <button type="submit" class="btn btn-success">Save</button>
          <a class="btn btn-outline-success" href="{{ url_for('entries.detail', slug=entry.slug) }}">Cancel</a>
        </div>
      </div>
    </form>
  
  <!-- End Container -->
  </div>
</section>
{% endblock %}

entries/templates/entries/index.html
{% extends "layout.html" %}


{% block main %}
<!-- Main Blog Page -->
<div class="container">
  <div class="row">

    <!-- Post Entries Column -->
    <div class="col-md-8">
      <h2 class="my-4">Blog</h2>
      <hr>
      <p class="lead" style="margin-bottom: 16px;">All blog posts</p>
      {% include "includes/_list.html" %}
      {% include "includes/_page_links.html" %}
    </div>


    <!-- Sidebar Column -->
    <div class="col-md-4">
      {% include "includes/_search.html" %}
      <!-- Posts Categories -->
      <div class="card my-4">
        <h5 class="card-header"><a href="{{ url_for('entries.tag_index') }}">Categories</a></h5>
        <ul class="list-group list-group-flush">
          {% for tag, tag_index in tags %}
          <li class="list-group-item d-flex justify-content-between align-items-center">
            <a href="{{ url_for('entries.tag_detail', slug=tag.slug)}}">{{ tag.name }}</a>
            <a href="{{ url_for('entries.tag_detail', slug=tag.slug)}}" class="badge badge-primary badge-pill">{{ tag_index }}</a>
          </li>
          {% endfor %}
        </ul>
      </div>
      <!-- Side Widget -->
      <div class="card my-4">
        <h5 class="card-header">Side Widget</h5>
        <div class="card-body">
          You can put anything you want inside of these side widgets. They are easy to use, and feature
          the new Bootstrap 4 card containers!
        </div>
      </div>
    </div>

    <!-- End Row -->
  </div>
  <!-- End Container -->
</div>
{% endblock %}

entries/templates/entries/tag_detail.html
{% extends "layout.html" %}


{% block main %}
<!-- Category Page -->
<div class="container">
    <div class="row">

        <!-- Posts Column -->
        <div class="col-md-8">
            <h2 class="my-4"> {{ tag.name }}
                <small>category</small>
            </h2>
            {% include "includes/_list.html" %}
            {% include "includes/_page_links.html" %}
        </div>


        <!-- Sidebar Column -->
        <div class="col-md-4">
            <!-- Search Widget -->
            {% include "includes/_search.html" %}
        </div>
    </div>
</div>
{% endblock %}

entries/templates/entries/tag_index.html
{% extends "layout.html" %}


{% block main %}
<!-- Categories Page -->
<div class="container">
  <div class="row">

    <div class="col-12">
      <div class="card my-4">
        <h5 class="card-header">Categories</h5>
        <div class="card-body d-flex justify-content-between align-items-center">
          <ul class="list-unstyled mb-0">
            {% for tag in object_list.items %}
            <li class="card-title"><a href="{{ url_for('entries.tag_detail', slug=tag.slug)}}">{{ tag.name }}</a></li>
            {% endfor %}
          </ul>
          <ul class="list-unstyled mb-0">
            {% for tag_index in tags_index %}
            <li class="card-title font-weight-bold">{{ tag_index }}</li>
            {% endfor %}
          </ul>
        </div>
      </div>
      {% include "includes/_page_links.html" %}
    </div>

    <!-- End Row -->
  </div>
  <!-- End Container -->
</div>
{% endblock %}